"""
ffuf container runner -- fast content discovery via the Docker ffuf image.

Wraps the harness/ffuf:2.1.0 Docker image (built by tools/ffuf.Dockerfile) as a
deterministic, code-built invocation through tool_runner.  The harness composes the
exact argv; ffuf never sees an LLM-generated string.

Usage in the pipeline: SurfaceDiscovery.discover() calls ffuf_discover() as a
fast-path before (or instead of) its own Python probe sweep when Docker + the image
are available.  The routes are fed into the same SurfaceResult, tagged source="ffuf".

The wordlist is baked into the image at /wordlist.txt (generated by
tools/gen_ffuf_wordlist.py); scope (target URL) and identity headers are passed at
run time.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

from harness import tool_runner
from harness.api_surface_discovery import Route

logger = logging.getLogger(__name__)

DEFAULT_IMAGE = "harness/ffuf:2.1.0"
DEFAULT_WORDLIST = "/wordlist.txt"
DEFAULT_THREADS = 40
DEFAULT_TIMEOUT = 180.0


@dataclass
class FfufResult:
    routes: list[Route] = field(default_factory=list)
    raw_stdout: str = ""
    raw_stderr: str = ""
    returncode: int = -1
    error: str | None = None
    used_fallback: bool = False   # #10: the strict-JSON parse found nothing and we
                                  # fell back to the line parser -- surfaced so a
                                  # caller never silently trusts scavenged output.


def ffuf_available(image: str = DEFAULT_IMAGE) -> tuple[bool, str]:
    """Check whether Docker is up AND the ffuf image is present."""
    ok, reason = tool_runner.available()
    if not ok:
        return False, reason
    if not tool_runner.image_present(image):
        return False, f"ffuf image {image!r} not found locally"
    return True, "ok"


def build_args(target_url: str, *, wordlist: str = DEFAULT_WORDLIST,
               threads: int = DEFAULT_THREADS, headers: dict[str, str] | None = None,
               match_codes: str = "all", filter_codes: str = "404",
               auto_calibrate: bool = True) -> list[str]:
    """Build the ffuf argument list.  Pure -- no side effects, testable."""
    url = tool_runner.localhost_url(target_url.rstrip("/") + "/FUZZ")
    args = [
        "-u", url,
        "-w", wordlist,
        "-mc", match_codes,
        "-fc", filter_codes,
        "-t", str(threads),
        "-s",           # silent: one result per line (FUZZ value only)
        "-json",        # JSON output on stdout (one JSON object per line)
    ]
    if auto_calibrate:
        args.append("-ac")
    for name, value in (headers or {}).items():
        args.extend(["-H", f"{name}: {value}"])
    return args


def parse_json_lines(stdout: str) -> list[Route]:
    """Parse ffuf's -json output (one JSON object per line) into Route objects."""
    routes: list[Route] = []
    for line in stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except (json.JSONDecodeError, ValueError):
            continue
        input_data = obj.get("input", {})
        fuzz_val = input_data.get("FUZZ", "")
        if not fuzz_val:
            continue
        path = "/" + fuzz_val.lstrip("/")
        status = obj.get("status", 0)
        length = obj.get("length", 0)
        routes.append(Route(path=path, status=status, length=length, source="ffuf"))
    return routes


def _looks_like_fuzz_value(line: str) -> bool:
    """A real ffuf -s line is a SINGLE FUZZ path token. Reject anything that looks
    like diagnostic/log output (#10) -- whitespace, a URL scheme, ANSI/brackets, an
    over-long line -- so arbitrary stderr-on-stdout noise never becomes a bogus path."""
    if not line or len(line) > 256:
        return False
    if any(c.isspace() for c in line):          # a path token has no spaces/tabs
        return False
    if "://" in line or line.startswith(("[", "*", "-", "#", "{", "}")):
        return False
    # printable path-ish characters only
    return all(32 < ord(c) < 127 for c in line)


def parse_silent_lines(stdout: str) -> list[Route]:
    """STRICT fallback parser for -s (silent, no -json) output: one FUZZ value per
    line, but only lines that actually look like a FUZZ path token (#10). Arbitrary
    non-path output is dropped rather than turned into a fabricated route."""
    routes: list[Route] = []
    for line in stdout.splitlines():
        line = line.strip()
        if not _looks_like_fuzz_value(line):
            continue
        path = "/" + line.lstrip("/")
        routes.append(Route(path=path, source="ffuf"))
    return routes


def run_sync(target_url: str, *, image: str = DEFAULT_IMAGE,
             wordlist: str = DEFAULT_WORDLIST, threads: int = DEFAULT_THREADS,
             headers: dict[str, str] | None = None, timeout: float = DEFAULT_TIMEOUT,
             match_codes: str = "all", filter_codes: str = "404",
             auto_calibrate: bool = True) -> FfufResult:
    """Run ffuf in a container and return parsed routes.  Synchronous (blocks)."""
    args = build_args(target_url, wordlist=wordlist, threads=threads,
                      headers=headers, match_codes=match_codes,
                      filter_codes=filter_codes, auto_calibrate=auto_calibrate)
    try:
        rc, stdout, stderr = tool_runner.run(image, args, timeout=timeout)
    except Exception as e:
        return FfufResult(error=f"ffuf container failed: {e}")

    result = FfufResult(raw_stdout=stdout, raw_stderr=stderr, returncode=rc)

    if rc != 0 and not stdout.strip():
        result.error = f"ffuf exited {rc}: {stderr[:500]}"
        return result

    result.routes = parse_json_lines(stdout)
    if not result.routes:
        result.routes = parse_silent_lines(stdout)
        result.used_fallback = bool(result.routes)   # #10: surface fallback use
    return result


async def ffuf_discover(target_url: str, *, image: str = DEFAULT_IMAGE,
                        headers: dict[str, str] | None = None,
                        timeout: float = DEFAULT_TIMEOUT) -> FfufResult:
    """Async wrapper: run ffuf in a thread so it doesn't block the event loop."""
    import asyncio
    return await asyncio.to_thread(
        run_sync, target_url, image=image, headers=headers, timeout=timeout)
